src/accounts/urls.py
from django.urls import path, include

from accounts import views, email_activation
from accounts.views import home, signup
from django.contrib.auth import views as auth_views
import django.contrib.auth.urls
app_name = "accounts"

urlpatterns = [
    path("", home, name="home"),
    path("accounts/signup/", signup, name="signup"),
    path("accounts/", include("django.contrib.auth.urls")),
    path('activate/<uidb64>/<token>', email_activation.activate, name='activate'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="registration/password_reset.html", email_template_name="registration/password_reset_email.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"), name="password_reset_complete"),

]

src/prospector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('accounts.urls')),
    path('', include('tracking.urls')),
]

src/prospector_app/urls.py
from django.urls import path, include
from prospector_app.views import home, signup
import django.contrib.auth.urls
app_name = "prospector"

urlpatterns = [
    path("", home, name="home"),
    path("accounts/signup/", signup, name="signup"),
    path("accounts/", include("django.contrib.auth.urls")),
]

src/tracking/urls.py
from django.urls import path

from tracking.views import dashboard, LeadsListView, OffersListView

app_name = "tracking"

urlpatterns = [
    path("tracking/", dashboard, name="dashboard"),
    path("tracking/leads/", LeadsListView.as_view(), name="leads"),
    path("tracking/offers/", OffersListView.as_view(), name="offers")
]

src/accounts/models.py
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser
from django.db import models


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return "user_{0}/{1}".format(instance.user.id, filename)


class CustomUser(AbstractUser):
    email = models.EmailField(_("email address"), unique=True, blank=True)
    curriculum_vitae = models.FileField(_("resume"), upload_to=user_directory_path)
    linkedin_link = models.URLField(_("linkedin link"), max_length=200)
    prospection_email = models.EmailField(_("email address for prospection"), blank=True)
    prospection_password = models.CharField(_("prospection password"), max_length=128, blank=True)

    @staticmethod
    def get_absolute_url():
        return reverse('accounts:home')

src/tracking/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from prospector import settings


class Leads(models.Model):
    lead_status = (
        ("", _("Empty")),
        ("invited", _("Invitation/Email sent")),
        ("match", _("Contact initiated")),
        ("call", _("Call planned")),
        ("technical_interview_1", _("Technical Interview Software Firm")),
        ("technical_interview_2", _("Technical Interview final client")),
        ("interview", _("Interview")),
        ("offer", _("Offer")),
        ("ko", _("KO")),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    first_name = models.CharField(_("first name"), max_length=150)
    last_name = models.CharField(_("last name"), max_length=150, blank=True)
    email = models.EmailField(_("email adress"), blank=True)
    company = models.CharField(_("company"), blank=True, max_length=50)
    status = models.CharField(_("lead status"), choices=lead_status, default="", max_length=50)
    source = models.CharField(_("source"), blank=True, max_length=150)
    date_last_contact = models.DateField(_("Last contact date"))
    date_reminder = models.DateField(_("Next reminder date"))
    status_reminder = models.CharField(_("Reminder status"), max_length=50)


class Offers(models.Model):
    experience = (
        ("0-2", _("0-2 years")),
        ("2-5", _("2-5 years")),
        ("5-10", _("5-10 years")),
    )

    work_rhythm_choices = (
        ("0", _("In person")),
        ("1", _("Hybrid")),
        ("2", _("Full Remote")),
    )

    lead = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=150, blank=False, null=False)
    date_offer = models.DateField(_("Date of offer publication"))
    offer_market = models.CharField(_("Market"), blank=False, max_length=100)
    location = models.CharField(_("Location"), max_length=150)
    experience = models.CharField(_("experience"), choices=experience, max_length=50)
    average_daily_rate = models.IntegerField()
    work_rhythm = models.CharField(_("rhythm"), choices=work_rhythm_choices, max_length=100)
    offer_link = models.URLField()
    activity_area = models.CharField(max_length=100)
    mandatory_technos = models.CharField(max_length=150)
    optional_technos = models.CharField(max_length=150)
    mandatory_skill = models.CharField(max_length=150)
    optional_skill = models.CharField(max_length=150)
    notes = models.TextField()

src/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm

from accounts.models import CustomUser


class CustomSignupForm(UserCreationForm):
    """
        Customisation of the built-in SignupForm in Django by
        changing the user model used from User -> CustomUser
    """
    class Meta:
        model = CustomUser
        fields = ("username", "email", "password1", "password2",)
        # fields = UserCreationForm.Meta.fields

src/prospector_app/forms.py
from django.contrib.auth.forms import UserCreationForm

from prospector_app.models import CustomUser


class CustomSignupForm(UserCreationForm):
    """
        Customisation of the built-in SignupForm in Django by
        changing the user model used from User -> CustomUser
    """
    class Meta:
        model = CustomUser
        fields = UserCreationForm.Meta.fields

src/accounts/views.py
from django.shortcuts import render, redirect

from accounts.email_activation import activateEmail
from accounts.forms import CustomSignupForm


# Create your views here.
def home(request):
    return render(request, "home.html")


def signup(request):
    context = {}
    if request.method == "POST":
        form = CustomSignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            activateEmail(request, user, form.cleaned_data.get('email'))
            return redirect("accounts:login")
        else:
            context["errors"] = form.errors

    form = CustomSignupForm()
    context["form"] = form

    return render(request, "accounts/signup.html", context=context)

src/prospector_app/views.py
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.shortcuts import render

from prospector_app.forms import CustomSignupForm
from prospector_app.models import CustomUser


# Create your views here.
def home(request):
    return render(request, "home.html")


def signup(request):
    context = {}

    if request.method == "POST":
        form = CustomSignupForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse("Bienvenue !")
        else:
            context["errors"] = form.errors

    form = CustomSignupForm()
    context["form"] = form

    return render(request, "accounts/signup.html", context=context)

src/tracking/views.py
from django.shortcuts import render
from django.views.generic import ListView

from tracking.models import Leads, Offers


# Create your views here.


def dashboard(request):
    return render(request, 'dashboard.html')


class LeadsListView(ListView):
    template_name = "leads.html"
    model = Leads

class OffersListView(ListView):
    template_name = "offers.html"
    model = Offers

src/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}
    <title>Créer un compte</title>
{% endblock %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    {% for message in errors.values %}
        <h3 style="color: red;">
            {{ message }}
        </h3>
    {% endfor %}

    <input type="submit" value="S'inscrire">

    <p>Déjà un compte ? <a href="{% url 'accounts:login' %}">Connectez-vous</a></p>
</form>

{% endblock %}

src/accounts/templates/activate_account/template_activate_account.html
{% autoescape off %}
Salut {{ user }},

Clique sur ce lien pour confirmer ton inscription :

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

src/accounts/templates/home.html
{% extends "base.html" %}

{% block title %}
    <title>Accueil</title>
{% endblock %}

{% block content %}
    <h1>Home</h1>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>Prospector</title>
    {% endblock %}
</head>

<body>
<nav>
    <ul>
        <li>
            <a href="{% url 'accounts:home' %}">Accueil</a>
        </li>
        {% if not request.user.is_authenticated %}
            <li>
                <a href="{% url 'accounts:login' %}">Connexion</a>
            </li>
            <li>
                <a href="{% url 'accounts:signup' %}">Inscription</a>
            </li>
        {% endif %}

        {% if request.user.is_authenticated %}
            <li>
                <a href="{% url 'accounts:logout' %}">Déconnexion</a>
            </li>
       {% endif %}
    </ul>
</nav>

{% for message in messages %}
{% if message.tags == 'error' %}
    <div class="" role="alert">
        {{ message }}
    </div>
    {% elif message.tags == 'success' %}
    <div class="" role="alert">
        {{ message }}
    </div>
    {% endif %}
{% endfor %}
<section id="prospector">
    {% block content %}
    {% endblock %}
</section>

</body>
</html>

src/tracking/templates/dashboard.html
<h1>dashboard</h1>

src/tracking/templates/leads.html
{% extends 'base.html' %}

{% block title %}
<title>Leads</title>
{% endblock %}

{% block content %}
<h1>Leads</h1>
{% endblock %}

src/tracking/templates/offers.html
{% extends 'base.html' %}

{% block title %}
<title>Offers</title>
{% endblock %}

{% block content %}
<h1>Offers</h1>
{% endblock %}